<?php

namespace App\Http\Controllers;

use App\Models\StockNotification;
use App\Http\Controllers\DatabaseSeederController;
use Illuminate\Support\Facades\Log;

class StockNotificationController extends Controller
{
    // ✅ Get all active notifications with auto-seeding
    public function index()
    {
        // Ensure base data exists first
        if (\App\Models\Product::count() === 0) {
            DatabaseSeederController::seedMissingData();
        }
        
        // If no notifications, that's fine - return empty array
        // Notifications are typically auto-generated by the system
        $notifications = StockNotification::where('is_read', false)->get();
        
        return response()->json($notifications);
    }

    // ✅ Mark notification as read
    public function markAsRead(StockNotification $notification)
    {
        $notification->update(['is_read' => true]);
        return response()->json(['message' => 'Notification marked as read']);
    }
}
